---
- name: find old units
  become: true
  shell: (grep -l "#MANAGED BY ANSIBLE" -r /etc/systemd/system/; find /etc/systemd/system/ -type f -name 'voctomix-*') | xargs -rl1 basename
  register: old_units

- debug: 
    msg: "{{ old_units.stdout_lines }}"

# directories & code
- name: create voctomix directories
  become: true
  file:
    dest: "{{ item }}"
    state: directory
    owner: root
    group: root
    recurse: true
  with_items:
      - /opt/voc/scripts/
      - /opt/voc/release/
      - /video/capture/{{ voc_event_acronym }}
      - /video/encoded/{{ voc_event_acronym }}
      - /video/tmp/{{ voc_event_acronym }}
      - /video/intros/{{ voc_event_acronym }}
      - /video/fuse/{{ voc_event_acronym }}


# decklink sources
- name: deploy decklink-format-detection-script
  become: true
  template:
    src: "voctomix-scripts/ffmpeg-detect-mode-number.sh.j2"
    dest: "/opt/voc/scripts/ffmpeg-detect-mode-number.sh"
    mode: 0755
    owner: root
    group: root

- name: deploy decklink-format-test-all-script
  become: true
  template: 
    src: "voctomix-scripts/ffmpeg-test-all-decklink-modes.sh.j2"
    dest: "/opt/voc/scripts/ffmpeg-test-all-decklink-modes.sh"
    mode: 0755
    owner: root
    group: root


  # recording sink
- name: create recording script
  template: 
    src: "toolbox-scripts/recording-sink.sh.j2"
              dest="/opt/voc/scripts/recording-sink.sh"
              mode=0750 owner=root group=root

  - name: create recording systemd-unit
    template: src="systemd-units/recording-sink.service.j2"
              dest="/etc/systemd/system/recording-sink.service"
              mode=0644 owner=root group=root

  - name: enable recording service
    service: name=recording-sink.service
             enabled=yes

  # check recording - called via check_system script (common role)
  - name: copy check_recording script
    copy: src="check_recording.pl"
          dest="/usr/local/bin/check_recording.pl"
          mode=0755 owner=root group=root
    tags:
      - check_recording

  - file: src=/usr/local/sbin/check_system.sh
        dest=/opt/voctomix/scripts/check_recording.sh
        state=link
    tags:
      - check_recording




