---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- include_tasks: general.yml
  when: encoders_general_setup|bool

- include_tasks: packages.yml
  when: encoders_general_setup|bool

