---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- include_tasks: general.yml
  when: encoders_general_setup|bool

- include_tasks: packages.yml
  when: encoders_general_setup|bool

- include_tasks: encodermode-voctomix.yml
  when: encoders_voctomix_setup_advanced_random_services|bool

- include_tasks: basic-toolbox-mode-voctomix.yml
  when: not  encoders_voctomix_setup_advanced_random_services|bool

- include_tasks: rsync.yml
  when: rsync_video_files | bool

